# Generated by Django 4.1.5 on 2023-01-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookweb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Book',
        ),
    ]
