# Generated by Django 4.1.5 on 2023-01-13 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookweb_app', '0009_review_review_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
