# Generated by Django 4.1.5 on 2023-01-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookweb_app', '0010_alter_review_review_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='no_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
